# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "posix-getopt-1.2.0" = {
      name = "posix-getopt";
      packageName = "posix-getopt";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/posix-getopt/-/posix-getopt-1.2.0.tgz";
        sha1 = "4aeeeb7dade66fca8a9365dda9f6b005741cb621";
      };
    };
  };
in
{
  smfgen = nodeEnv.buildNodePackage {
    name = "smfgen";
    packageName = "smfgen";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/smfgen/-/smfgen-1.2.0.tgz";
      sha512 = "skRknTUi9cTc6KKSlTt1WTX0E7gJ+oyMG5ndifQf6QuoK87gSxAxAAvf6Lc/T0vaw96lxIsfzh49EP7yt6EWig==";
    };
    dependencies = [
      sources."assert-plus-1.0.0"
      sources."posix-getopt-1.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Generate an SMF manifest from a JSON or CLI description of the service";
      homepage = "https://github.com/joyent/smfgen#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
